name: Build

on:
  push:
    branches:
      - main
      - master
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ubuntu-clang:
    name: Ubuntu Clang
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y clang cmake ninja-build

      - name: Configure
        run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release
        env:
          CC: clang
          CXX: clang++

      - name: Build
        run: cmake --build build --config Release --parallel

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: XenosRecomp-ubuntu-clang
          path: build/XenosRecomp/XenosRecomp
          if-no-files-found: error

  windows-msvc:
    name: Windows MSVC
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure
        run: cmake -S . -B build -A x64

      - name: Build
        run: cmake --build build --config Release --parallel

      - name: Upload executables
        uses: actions/upload-artifact@v4
        with:
          name: XenosRecomp-windows-msvc
          path: |
            build/XenosRecomp/Release/XenosRecomp.exe
            build/XenosRecomp/Release/XenosRecompGui.exe
            build/XenosRecomp/Release/*.dll
          if-no-files-found: error
